language: python


matrix:
  include:
    - name: "ubuntu xenial"
      os: linux  
      dist: xenial
    - name: "ubuntu bionic"
      os: linux
      dist: bionic

python:
  - "3.6"

install:
  - sudo apt-get update
  # miniconda install
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  # miniconda setup
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -y -q conda
  - conda config --add channels defaults
  - conda config --add channels conda-forge
  - conda config --add channels bioconda
  - conda info -a
  # conda env setup
  - conda create -n DeepMAsED --yes python=$TRAVIS_PYTHON_VERSION tensorflow=2.0 tensorboard keras scikit-learn ipython pytest snakemake
  - conda activate DeepMAsED
  # DeepMAsED install
  - python setup.py build_ext --inplace
  - python setup.py build
  - python setup.py install
  - conda list

script:
  - pytest
  - bash DeepMAsED-SM/tests/data/read_n6_dl.sh
  - snakemake --directory DeepMAsED-SM --snakefile DeepMAsED-SM/Snakefile -F --dryrun
