name: deepmased
channels:
  - anaconda
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - absl-py=0.1.13=py36_0
  - astor=0.6.2=py36_0
  - biopython=1.69=np113py36_0
  - cudatoolkit=8.0=3
  - cudnn=7.0.5=cuda8.0_0
  - cupti=8.0.61=0
  - decorator=4.2.1=py36_0
  - gast=0.2.0=py36_0
  - grpcio=1.11.0=py36hf484d3e_0
  - h5py=2.7.1=py36h3585f63_0
  - hdf5=1.10.1=h9caa474_1
  - intel-openmp=2018.0.0=h15fc484_7
  - ipython=6.2.1=py36h88c514a_1
  - ipython_genutils=0.2.0=py36hb52b0d5_0
  - jedi=0.11.1=py36_0
  - libedit=3.1=heed3624_0
  - libffi=3.2.1=h4deb6c0_3
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=7.2.0=h7cc24e2_2
  - libgfortran-ng=7.2.0=h9f7466a_2
  - libprotobuf=3.4.0=0
  - libstdcxx-ng=7.2.0=h7a57d05_2
  - mkl=2018.0.2=1
  - ncurses=6.0=h06874d7_1
  - parso=0.1.1=py36h35f843b_0
  - pexpect=4.3.1=py36_0
  - pickleshare=0.7.4=py36h63277f8_0
  - prompt_toolkit=1.0.15=py36h17d85b1_0
  - ptyprocess=0.5.2=py36h69acd42_0
  - pygments=2.2.0=py36h0d3125c_0
  - pyyaml=3.12=py36hafb9ca4_1
  - readline=7.0=hac23ff0_3
  - simplegeneric=0.8.1=py36_1
  - sqlite=3.20.1=h6d8b0f3_1
  - termcolor=1.1.0=py36_1
  - tk=8.6.7=h5979e9b_1
  - traitlets=4.3.2=py36h674d592_0
  - wcwidth=0.1.7=py36hdf4376a_0
  - yaml=0.1.7=had09818_2
  - zlib=1.2.11=hfbfcf68_1
  - bcftools=1.6=1
  - htslib=1.7=0
  - pysam=0.14.0=py36_htslib1.7_2
  - samtools=1.7=1
  - backports=1.0=py36_1
  - backports.weakref=1.0rc1=py36_1
  - bleach=1.5.0=py36_0
  - bzip2=1.0.6=1
  - ca-certificates=2018.4.16=0
  - certifi=2018.4.16=py36_0
  - curl=7.59.0=0
  - cycler=0.10.0=py36_0
  - dbus=1.11.0=0
  - expat=2.2.5=0
  - fontconfig=2.12.6=0
  - freetype=2.8.1=0
  - funcsigs=1.0.2=py_2
  - gettext=0.19.8.1=0
  - glib=2.55.0=0
  - gst-plugins-base=1.8.0=0
  - gstreamer=1.8.0=1
  - html5lib=0.9999999=py36_0
  - icu=58.2=0
  - jpeg=9b=2
  - kiwisolver=1.0.1=py36_1
  - krb5=1.14.2=0
  - libiconv=1.15=0
  - libpng=1.6.34=0
  - libssh2=1.8.0=2
  - libxcb=1.13=0
  - libxml2=2.9.8=0
  - matplotlib=2.2.2=py36_1
  - mkl_fft=1.0.2=py36_0
  - mkl_random=1.0.1=py36_0
  - mock=2.0.0=py36_0
  - openblas=0.2.20=7
  - openssl=1.0.2o=0
  - pbr=3.1.1=py36_0
  - pcre=8.41=1
  - pip=9.0.1=py36_0
  - protobuf=3.5.1=py36_3
  - pyparsing=2.2.0=py36_0
  - pyqt=5.6.0=py36_5
  - python-dateutil=2.7.2=py_0
  - pytz=2018.4=py_0
  - qt=5.6.2=7
  - setuptools=36.3.0=py36_0
  - sip=4.18=py36_1
  - six=1.11.0=py36_1
  - tornado=5.0.2=py36_0
  - tqdm=4.19.2=py_0
  - webencodings=0.5=py36_0
  - werkzeug=0.12.2=py_1
  - wheel=0.30.0=py_1
  - xorg-libxau=1.0.8=3
  - xorg-libxdmcp=1.1.2=3
  - xz=5.2.3=0
  - blas=1.0=mkl
  - libgfortran=3.0.0=1
  - markdown=2.6.9=py36_0
  - numpy=1.13.3=py36hdbf6ddf_4
  - python=3.6.3=hcad60d5_0
  - scikit-learn=0.19.1=py36h7aa7ec6_0
  - scipy=1.1.0=py36hfc37229_0
  - tensorboard=1.7.0=py36hf484d3e_0
  - tensorflow-gpu=1.7.0=0
  - tensorflow-gpu-base=1.7.0=py36h5b7bae4_1
  - tensorflow-tensorboard=0.1.5=py36_0
  - pip:
    - appdirs==1.4.3
    - autograd==1.2
    - biolib==0.0.46
    - chardet==3.0.4
    - comparem==0.0.23
    - deeplift==0.6.9.0
    - future==0.16.0
    - idna==2.8
    - imageio==2.5.0
    - keras==2.2.4
    - keras-applications==1.0.7
    - keras-preprocessing==1.0.9
    - keras-vis==0.4.1
    - nanosim-h==1.1.0.4
    - ncbi-genome-download==0.2.9
    - networkx==2.3
    - pandas==0.24.2
    - pillow==6.1.0
    - progressbar2==3.38.0
    - psutil==5.4.8
    - pyarrow==0.9.0
    - pybigwig==0.3.16
    - python-utils==2.3.0
    - pywavelets==1.0.3
    - pyzmq==17.0.0
    - requests==2.21.0
    - scikit-image==0.15.0
    - seaborn==0.9.0
    - tabulate==0.8.2
    - tensorflow==1.7.0
    - tensorpack==0.8.6
    - treelib==1.5.2
    - upsetplot==0.3.0.post3
    - urllib3==1.24.1

